### ISSUE TITLE
Could not find SparkEventLogParser-slim-1.0.jar in emr-serverless-estimator

### ISSUE THREAD

**Issue by Ghoul-SSZ** [aws-samples/aws-emr-utilities#6]
Hi, I think when you created the emr-serverless-estimator project. The .gitignore actually prevented upload jar files. 

Also, I could not seem to find SparkEventLogParser-slim-1.0.jar in Maven Central Either. 

Can you help explaining where can I find those jars in order to run the estimator? (Or upload the jar to the repo if it is not too big)

Thank you and have a nice day. :)

**Comment by nc24** [comment]
+1, can you add in the jar files or point to the location.

**Comment by Ghoul-SSZ** [comment]
seem like the jar can be found in  https://github.com/aws-samples/aws-emr-utilities/releases/
